### PR TITLE
Update API and add .gitignore

### PR DESCRIPTION
**Pull request by levibotelho**
Updated the API to use async methods, and added a proper .gitignore as not to publish .dlls.

### CODE REVIEW

**Comment by erikbartlow** [comment]
Does this contain your improvements for a better c# library?

**Comment by levibotelho** [comment]
Yeah. It can definitely be taken further, as I didn't rewrite the documentation comments to be in XML format or replace the dictionaries with typed objects, but it gets rid of the dynamics and adds async/await support.

**Comment by madmox** [comment]
Whoa, you definitely should improve this C# API. In the current state, we can't possibly integrate this code into our production app. This PR is a good start, although it lacks a few things:
- POCOs to avoid having a `Dictionary<string, object> data` parameter on each method (more explicit signatures)
- Real unit tests (do not use a console app to provide unit tests...) & fix cross-project references
- A nuget package...

**Comment by levibotelho** [comment]
@madmox totally agree. I don't work for sendinblue so don't intend to invest more time into this, and really at the very least the NuGet package should be sendinblue's job.

Having said that if you do want to make any improvements to this PR that'd be cool as I could integrate them into my own codebase 😄.

**Comment by maftieu** [comment]
I was looking for something like this. I will try it.
@mailin-api please merge this PR to update your library. It is currently soooo not C#.

**Comment by ekta-slit** [comment]
As part of the sendinblue API version 2 deprecation plan this repository is no longer supported. Please refer to its updated version 3: https://github.com/sendinblue/APIv3-csharp-library

**Pull request closed without merging**
